### PR TITLE
some improvements

### PR DESCRIPTION
**Pull request by mopi1402**
- removed unused device_info_plus
- added linter
- fix all linter hints
- updated ios project

It's should use less memory and might be faster because I used const and final.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1010) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1010) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/MMKV?pullRequest=1010) it.</sub>

**Comment by lingol** [comment]
Two small problems.
* We don't accept PRs to the `master` branch, you should change the target to `dev` branch.
* Breaking changes should be avoided if possible. The naming changes in enum cases are non-essential. The [rule](https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names) is a _PREFER_ rule after all.

**Comment by mopi1402** [comment]
Thank you for the reply. So there is no breaking change anymore.

**Comment by lingol** [comment]
Hi, the PR looks good to me except for a tiny conflict you should take care of. https://github.com/Tencent/MMKV/pull/1010/conflicts

**Comment by mopi1402** [comment]
done :)

**Review by Navarro69 — APPROVED** [review]

**Pull request merged**
