### PR TITLE
feat: `hasValue` out parameter

### LINKED ISSUE #827: Default Value of `nullptr` for non-reference-type functions
### The language of MMKV

Objective-C and C++

### The version of MMKV

Current master

### The platform of MMKV

iOS and Android

### The installation of MMKV

Cocoapods and Git Submodule

### Question

The `getString(..)` function returns a `bool` value, where `true` means the key exists in storage and `false` means it doesn't.

I would love to have the same functionality for non-reference-type type functions, for example for the `getDouble(..)` or `getBoolean(..)`, and am proposing two APIs:

#### API 1

This is a **breaking change**, but would align with the `getString(..)` API.

```c++
// getString(...)
std::string result;
bool hasValue = instance->getString(keyName, result);
------
// getDouble(...)
double result;
bool hasValue = instance->getDouble(keyName, &result);
```

#### API 2

This is **non-breaking**, but uses a different API than the `getString(..)` function:

```c++
// getString(...)
std::string result;
bool hasValue = instance->getString(keyName, result);
------
// getDouble(...)
bool hasValue;
double result = instance->getDouble(keyName, &hasValue);
```

@lingol I would love to hear your thoughts on this, if you are in favor of implementing this functionality, let me know and maybe I can come up with a draft PR to kick things off. :)

### PR DESCRIPTION
**Pull request by mrousavy**
Adds a new parameter to non-reference type getter functions to find out if they have a value or are returning the default value passed in:

* `getBool(..)`
* `getInt32(..)`
* `getUInt32(..)`
* `getInt64(..)`
* `getUInt64(..)`
* `getFloat(..)`
* `getDouble(..)`

Usage:

```cpp
bool hasValue;
double value = instance->getDouble("myKey", 0.0, &hasValue);

if (hasValue) {
  ...
} else {
  ...
}
```

Since this is an optional parameter, it is a non-breaking API change.

* closes #827

### CODE REVIEW

**Comment by mrousavy** [comment]
@lingol what do you think about the `#define OUT` for better function signatures?

**Comment by mrousavy** [comment]
Also let me know if you prefer `&` or `*` for those parameters.

**Comment by lingol** [comment]
Passing by pointer is better than reference because it allows default to nullptr. The `OUT` macro is fine.

You have to make the pr to the dev branch though.

**Comment by lingol** [comment]
Oh, one more thing, the following week is Chinese New Year. So I won't be reviewing pr in time.

**Comment by mrousavy** [comment]
No worries, happy new year to you! 🎆

**Comment by mrousavy** [comment]
@lingol ah I just noticed that we also need to update the iOS and Android (and Flutter?) APIs, I only implemented it for C++ for now...

**Comment by lingol** [comment]
Never mind. I will add those later.

**Comment by mrousavy** [comment]
Hey @lingol, do you have any timeline for a coming release? Do you want me to shoot you a PR with the changes for iOS and Android as well?

**Pull request merged**
