### PR TITLE
Add LRU policy for memory cache.

### PR DESCRIPTION
**Pull request by longjianjiang**

### CODE REVIEW

**Comment by lingol** [comment]
Adding LRU logic for memory cache consumes considerable memory. Yet provides little functionality improvement to users.
Why are you doing this?

**Comment by lingol** [comment]
And by saying it consumes considerable memory, I mean using a double linked list to track the order of each node.

**Comment by longjianjiang** [comment]
Be honest, I saw you write `LRU cache for MMKV instances` in projects section, so i add this LRU logic.
Right now LRU didn't have `removeTailNode:` method, because file size will be doubled when size is not large enough for future usage. mmkv didn't provide limit control by the way.

**Comment by lingol** [comment]
That `LRU cache for MMKV instances` means for MMKV's instance, not for the key-values inside it. I'm afraid there's some misunderstanding.

**Pull request closed without merging**
