### PR TITLE
Get current process name for AppStore review

### PR DESCRIPTION
**Pull request by fine1021**
ActivityManager.getRunningAppProcesses() 容易被应用商店合规判定为 非法获取其他进程信息，Android 9 以上Google已经提供了公开API来获取当前的进程名，不涉及任何违规问题，希望能合并下代码或者调整下mmkv中关于进程名获取的方式

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1350) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1350) before we can accept your contribution.<br/><hr/>**yexiaokang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/MMKV?pullRequest=1350) it.</sub>

**Comment by lingol** [comment]
Thanks for your contribution. We don't accept PRs into the master branch directly. 
Would you change the target branch to the dev branch? You may change your source branch to base from dev as well.

**Comment by fine1021** [comment]
> Thanks for your contribution. We don't accept PRs into the master branch directly. Would you change the target branch to the dev branch? You may change your source branch to base from dev as well.

已经调整了

**Comment by lingol** [comment]
There are too much unnecessary merge messages. Like I said, you might change your source brand to dev as well.

**Pull request closed without merging**
