### PR TITLE
Fix the main thread checker warning about applicationState in iOS

### PR DESCRIPTION
**Pull request by iiiCeBlink**
Main thread checker will raise the warning `-[UIApplication applicationState] must be used from main thread only`, if developers call `-[MMKV initWithMMapID:cryptKey:]` method in the non-main thread.

### CODE REVIEW

**Comment by lingol** [comment]
The state of `m_isInBackground ` is crucial, can't be set async I'm afraid.

**Comment by lingol** [comment]
By the way, that async can not be simply replaced with sync, because that will trigger potential deadlock.

**Comment by iiiCeBlink** [comment]
Yes, you're right. My solution is that adding flag to wait for the result of executing the async task when `-[MMKV initWithMMapID:cryptKey:]` method is called in the non-main thread. However, I don't think it's an elegant solution. Do you have any better idea?

**Comment by lingol** [comment]
Indeed no good. The `while` loop is just as bad as sync, if not worse. If you really want to solve the warning, which by the way is no harm as far as I can see & wildly used in WeChat App with no problem, you might consider using a global state of `-[UIApplication applicationState]`. And use a lock to keep it's accessing thread safe.

**Comment by iiiCeBlink** [comment]
Well, I don't think it's worth using a global variable with a lock. And I'll focus on the influence of the code. thx.

**Pull request closed without merging**
