### PR TITLE
support build python library on Windows

### PR DESCRIPTION
**Pull request by BeneficialCode**
Test on Windows with msvc compiler. Now I'm comming!

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1288) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1288) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: BeneficialCode<br/>:white_check_mark: lingol<br/>:white_check_mark: colmugx<br/>:x: xiezheng-XD<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/MMKV?pullRequest=1288) it.</sub>

**Comment by BeneficialCode** [comment]
I have signed the CLA already but the status is still pending. Recheck is not useful. I don't know the reason.

**Comment by lingol** [comment]
Hey, there are too many unnecessary commits in your PR. Please make sure you have the latest dev branch. 

Also, if you can make the optimization of code structure, I will be most grateful. https://github.com/Tencent/MMKV/pull/1287#issuecomment-2097895096

**Comment by BeneficialCode** [comment]
Okay, I will try my best.

**Pull request closed without merging**
