### PR TITLE
[Android] Make class `MMKV` fully mockable with `Mockito`

### PR DESCRIPTION
**Pull request by wxxion**
### Summary
As Mockito can't mock JNI native method, move all JNI native methods (and necessary impl) from class `MMKV` to a separate class `JNIDelegate` to make class `MMKV` fully mockable with Mockito.

### Testing
* build
* Create a test app with the generated `.aar` and try to initialize and operate an MMKV instance

### CODE REVIEW

**Comment by lingol** [comment]
Thanks for your contribution. However, I'm not interested in making yet another facade just to make a mock tool happy. If you really want to use that mock tool, you should probably make a feature request to the developer of it. Or you should add a facade on top of the existing MMKV class, with no JNI methods.

**Comment by wxxion** [comment]
The new class `JNIDelegate` is not a `public` class. It's just to encapsulate all JNI directly related functions. From this point of view, it's an improvement to clarify the role of class `MMKV` as the `public` interface for the whole library.

BTW, to raise a feature request to the leading mocking framework `Mockito` is worth trying but it's also more expensive. After all, to get it supported and have the internal version of it in use by my org upgraded will take time.

While to create a wrapper for `MMKV` (or just wrap the call to method involving native method) will work, but it also means the wrapper can't be well covered by UT due to the limitation with `Mockito`.

**Comment by lingol** [comment]
All of MMKV's JNI relative methods & members are hidden from end users. I don't think there's much necessary for further clarification here.
The cost of a feature request on the mock tool, and the cost of your own wrapper, is your problem. I think you have to eat it up. 

It's NOT a generic problem for common MMKV end users that this mock tool doesn't work well with MMKV.

**Comment by wxxion** [comment]
The methods causing problem are those `public native` methods in `MMKV` like `clearAll` (there are 8 such kind of methods).
But as there are available (but maybe ugly) workaround, it's fine to handle it as an unacceptable PR.

**Pull request closed without merging**
