### PR TITLE
Added custom path support

### PR DESCRIPTION
**Pull request by Sunnyyoung**

### CODE REVIEW

**Comment by lingol** [comment]
Now that custom folder is added, you got to think about mmkv’id uniqueness. What should happen to the same id with different folder?

**Comment by lingol** [comment]
By the way, keep ident the same by running `make format_code` on root dir. (Revert the changes it made on **Android** dir though.

**Comment by lingol** [comment]
Someone else has provide a better solution. I'm sorry to close this one.

**Comment by Sunnyyoung** [comment]
LGTM, Thanks!

**Pull request closed without merging**
