### PR TITLE
Feature/visionos support

### PR DESCRIPTION
**Pull request by cyrilbo**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1234) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1234) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/MMKV?pullRequest=1234) it.</sub>

**Comment by cyrilbo** [comment]
Hi @lingol , thanks for merging this PR ! 🙂 Do you have an idea when It could be released ?

**Comment by lingol** [comment]
Thanks for your contribution. Are you or your App in need of this visionOS support?

**Comment by lingol** [comment]
It's released with v1.3.4.

**Pull request merged**
