### PR TITLE
support build python library on Windows

### PR DESCRIPTION
**Pull request by BeneficialCode**
Test on Windows with msvc compiler.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1287) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/MMKV?pullRequest=1287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/MMKV?pullRequest=1287) it.</sub>

**Comment by BeneficialCode** [comment]
Continue pushing

**Comment by lingol** [comment]
Thanks for your contribution. However, there's too much duplication between POSIX/Python and Win32/Python. Can you make the duplication go away? Maybe move the Python out of POSIX?

>POSIX/
>Python/ (with potential modification to CMakeLists.txt to support both POSIX & Win32)
>Win32/

**Comment by lingol** [comment]
Also, we don't accept PRs into the master branch directly. Please change the target branch to the dev branch.

**Pull request closed without merging**
